### ISSUE TITLE
Version 1.1.x has corrupted pom file 

### ISSUE THREAD

**Issue by ktarasenko** [debop/joda-time-kotlin#2]
Version of kotlin stdlib is missing in the pom file on jcenter. Version 1.0.0 works for me 

 ```
<dependency>
   <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <scope>runtime</scope>
</dependency>
 ```

**Comment by debop** [comment]
Kotlin stdlib version move fast. so we not defined specified stdlib version.
You can choose your stdlib version.

**Comment by ktarasenko** [comment]
That's okay, but If pom file has dependency, it should also have version, otherwise pom file is mailformed and sync fails, at least for me.

**Comment by debop** [comment]
@ktarasenko check out 1.1.3 please

**Comment by ktarasenko** [comment]
Works for me. Thanks
