### ISSUE TITLE
Supports only API level 26 and higher

### ISSUE THREAD

**Issue by firstthumb** [debop/joda-time-kotlin#7]
For date calculation, it uses **java.time.format.DateTimeFormatter** class which is added with Android API Level 26 otherwise it crashes

**Comment by debop** [comment]
Hi @firstthumb, 
I have no experience Android API.
Do you have alternative solution?

**Comment by debop** [comment]
I will separate modules (based joda-time, based java 8 times) then you can use joda-time based with early Android version

**Comment by debop** [comment]
Try joda-time 2.0.0 - split Java 8 times to java-time module
