### ISSUE TITLE
Unresolved reference on Android Studio 3.4

### ISSUE THREAD

**Issue by AlanLarsson** [debop/joda-time-kotlin#9]
Updated Android Studio and suddenly the project couldn't build because it couldn't resolve org.joda

**Comment by debop** [comment]
What you use ? `koda-time` or `java-time` ?

if you use `koda-time`, you should add `joda-time` dependency in your project.
`koda-time` use `joda-time` as provided (implementation)

**Comment by AlanLarsson** [comment]
It had worked fine before without explicitly adding the joda-time dependency.
But adding it solved my issue.

**Comment by SogoGolf** [comment]
oh man thank you this saved our bacon today. after updating to Android Studio 3.4, updated gradle-wrapper etc etc, suddenly all the DateTime's spread across the code base stopped resolving! as with @AlanLarsson we didn't need a specific dependency on joda-time

this fixed it.

```
implementation 'joda-time:joda-time:2.10.2'
implementation 'com.github.debop:koda-time:2.0.0'
```
